### ISSUE TITLE
error import gpkg using web api

### ISSUE THREAD

**Issue by volaya** [locationtech/geogig#105]
I have an empty repo an try to import a geopackage

I begin a transaction and then use the import endpoint to import the geopackage, and the response is this

```
<task>
<id>4</id>
<status>FAILED</status>
<transactionId>30d7b635-abf1-43d1-82f2-583ea01b619c</transactionId>
<description>Importing GeoPackage database file.</description>
<atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8182/tasks/4.xml" type="application/xml"/>
<error>
<message>refSpec HEAD did not resolve to a tree</message>
<stackTrace>
<![CDATA[
java.lang.IllegalArgumentException: refSpec HEAD did not resolve to a tree
 at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
 at org.locationtech.geogig.api.plumbing.DiffIndex._call(DiffIndex.java:82)
 at org.locationtech.geogig.api.plumbing.DiffIndex._call(DiffIndex.java:30)
 at org.locationtech.geogig.api.AbstractGeoGigOp.call(AbstractGeoGigOp.java:133)
 at org.locationtech.geogig.repository.Index.getStaged(Index.java:297)
 at org.locationtech.geogig.storage.TransactionStagingArea.getStaged(TransactionStagingArea.java:104)
 at org.locationtech.geogig.api.porcelain.AddOp.stage(AddOp.java:92)
 at org.locationtech.geogig.api.porcelain.AddOp._call(AddOp.java:70)
 at org.locationtech.geogig.api.porcelain.AddOp._call(AddOp.java:44)
 at org.locationtech.geogig.api.AbstractGeoGigOp.call(AbstractGeoGigOp.java:133)
 at org.locationtech.geogig.geotools.geopkg.GeopkgDataStoreImportOp.callAdd(GeopkgDataStoreImportOp.java:80)
 at org.locationtech.geogig.geotools.geopkg.GeopkgDataStoreImportOp.callInternal(GeopkgDataStoreImportOp.java:64)
 at org.locationtech.geogig.geotools.geopkg.GeopkgDataStoreImportOp.callInternal(GeopkgDataStoreImportOp.java:35)
 at org.locationtech.geogig.geotools.plumbing.DataStoreImportOp._call(DataStoreImportOp.java:341)
 at org.locationtech.geogig.api.AbstractGeoGigOp.call(AbstractGeoGigOp.java:133)
 at org.locationtech.geogig.rest.AsyncContext$CommandCall.call(AsyncContext.java:240)
 at java.util.concurrent.FutureTask.run(Unknown Source)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
]]>
</stackTrace>
</error>
</task>
```

The geopackage can be imported without issues using the console.

**Comment by volaya** [comment]
If the geopackage is imported using the console and then exported using the interchange format, when trying to import changes using the interchange=true parameter in the webapi call, i get this

```
<task>
<id>2</id>
<status>FAILED</status>
<transactionId>76b90a22-afee-49f8-82bf-8a823b08c557</transactionId>
<description>Importing GeoPackage database file.</description>
<atom:link xmlns:atom="http://www.w3.org/2005/Atom" rel="alternate" href="http://localhost:8182/tasks/2.xml" type="application/xml"/>
<error>
<message>
Unable to import: Object does not exist: 2495ecbaa3db0ed67f196c3c62f1ff07b6156681 at D:\repo\.\.geogig\objects
</message>
<stackTrace>
<![CDATA[
org.locationtech.geogig.cli.CommandFailedException: Unable to import: Object does not exist: 2495ecbaa3db0ed67f196c3c62f1ff07b6156681 at D:\repo\.\.geogig\objects
 at org.locationtech.geogig.geotools.geopkg.GeopkgDataStoreAuditImportOp.callInternal(GeopkgDataStoreAuditImportOp.java:41)
 at org.locationtech.geogig.geotools.geopkg.GeopkgDataStoreAuditImportOp.callInternal(GeopkgDataStoreAuditImportOp.java:23)
 at org.locationtech.geogig.geotools.plumbing.DataStoreImportOp._call(DataStoreImportOp.java:341)
 at org.locationtech.geogig.api.AbstractGeoGigOp.call(AbstractGeoGigOp.java:133)
 at org.locationtech.geogig.rest.AsyncContext$CommandCall.call(AsyncContext.java:240)
 at java.util.concurrent.FutureTask.run(Unknown Source)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
 Caused by: java.lang.IllegalStateException: Unable to import: Object does not exist: 2495ecbaa3db0ed67f196c3c62f1ff07b6156681 at D:\repo\.\.geogig\objects
 at org.locationtech.geogig.geotools.geopkg.GeopkgAuditImport._call(GeopkgAuditImport.java:99)
 at org.locationtech.geogig.geotools.geopkg.GeopkgAuditImport._call(GeopkgAuditImport.java:23)
 at org.locationtech.geogig.api.AbstractGeoGigOp.call(AbstractGeoGigOp.java:133)
 at org.locationtech.geogig.geotools.geopkg.GeopkgDataStoreAuditImportOp.callInternal(GeopkgDataStoreAuditImportOp.java:38)
 ... 10 more
 Caused by: java.lang.IllegalArgumentException: Object does not exist: 2495ecbaa3db0ed67f196c3c62f1ff07b6156681 at D:\repo\.\.geogig\objects
 at org.locationtech.geogig.storage.bdbje.JEObjectDatabase.getRawInternal(JEObjectDatabase.java:371)
 at org.locationtech.geogig.storage.AbstractObjectStore.getRaw(AbstractObjectStore.java:198)
 at org.locationtech.geogig.storage.AbstractObjectStore.get(AbstractObjectStore.java:148)
 at org.locationtech.geogig.storage.AbstractObjectStore.get(AbstractObjectStore.java:96)
 at org.locationtech.geogig.storage.ForwardingObjectDatabase.get(ForwardingObjectDatabase.java:81)
 at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$ValueLoader.call(ObjectDatabaseCacheInterceptor.java:182)
 at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$ValueLoader.call(ObjectDatabaseCacheInterceptor.java:169)
 at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4742)
 at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
 at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
 at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
 at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
 at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
 at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4739)
 at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CacheHelper.get(ObjectDatabaseCacheInterceptor.java:221)
 at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CachingObjectDatabase.get(ObjectDatabaseCacheInterceptor.java:109)
 at org.locationtech.geogig.di.caching.ObjectDatabaseCacheInterceptor$CachingObjectDatabase.getCommit(ObjectDatabaseCacheInterceptor.java:129)
 at org.locationtech.geogig.geotools.geopkg.InterchangeFormat.importAuditLog(InterchangeFormat.java:275)
 at org.locationtech.geogig.geotools.geopkg.GeopkgAuditImport._call(GeopkgAuditImport.java:90)
 ... 13 more
]]>
</stackTrace>
</error>
</task>
```

The commitid that it says it cannot find is the one in the geogig_audited_tables table of the geopackage, but not the one corresponding to the exported commit (that is the table seems to be populated with a wrong sha). It is actually a wrong sha, and trying to run "geogig show" or "geogig cat" with it results in "refspec did not resolve to any object."

**Comment by jdgarrett** [comment]
I am unable to reproduce either of these errors.  For the first one, it looks like HEAD is either missing or pointing to some bad data, for the second one I'm not sure how it could have a sha that doesn't even exist in the repository.  Can you try with a clean geopackage and write down all the commands/urls you are using?

**Comment by volaya** [comment]
Import seems sto be working now. Probably it was my fault and I was doing something wrong. Havent been able to reproduce, so i am closing this
