### ISSUE TITLE
Can't create RocksDB backed repos with GeoServer 2.10.0 and GeoGig 1.1.1

### ISSUE THREAD

**Issue by emerkle826** [locationtech/geogig#353]
From Erik Martinsen on the dev mailing list:

> We have removed the PostgreSQL driver postgresql-9.4.1211.jar before installing the GeoServer 2.10 plugin.
>
> The GeoGig menu items in the left side loads as expected after restarting the GeoServer but when we try to create a file based GeoGig repository we get an error of this kind “Could not initialize class org.rocksdb.RocksDB” (further information is included in the attached file java_errors.txt).
>
> We have also tried to install the GeoServer 2.10 plugin from this link: https://github.com/locationtech/geogig/releases/download/v1.1.1/geoserver-2.10.x-geogig-plugin.zip but unfortunately with the same result.

Exception:
```
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.rocksdb.RocksDB
	at org.locationtech.geogig.rocksdb.RocksConnectionManager.connect(RocksConnectionManager.java:57)
	at org.locationtech.geogig.rocksdb.RocksConnectionManager.connect(RocksConnectionManager.java:36)
	at org.locationtech.geogig.storage.impl.ConnectionManager.acquire(ConnectionManager.java:61)
	at org.locationtech.geogig.rocksdb.RocksdbObjectStore.open(RocksdbObjectStore.java:102)
	at org.locationtech.geogig.rocksdb.RocksdbObjectStore.open(RocksdbObjectStore.java:91)
	at org.locationtech.geogig.rocksdb.RocksdbObjectDatabase.open(RocksdbObjectDatabase.java:70)
	at org.locationtech.geogig.storage.impl.ForwardingObjectDatabase.open(ForwardingObjectDatabase.java:43)
	at org.locationtech.geogig.repository.impl.RepositoryImpl.open(RepositoryImpl.java:127)
	at org.locationtech.geogig.porcelain.InitOp._call(InitOp.java:179)
	at org.locationtech.geogig.porcelain.InitOp._call(InitOp.java:64)
	at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154)
	at org.geogig.geoserver.config.RepositoryManager.create(RepositoryManager.java:341)
	at org.geogig.geoserver.config.RepositoryManager.save(RepositoryManager.java:320)
	at org.geogig.geoserver.web.repository.RepositoryEditFormPanel.onSave(RepositoryEditFormPanel.java:250)
	at org.geogig.geoserver.web.repository.RepositoryEditFormPanel.access$000(RepositoryEditFormPanel.java:54)
	at org.geogig.geoserver.web.repository.RepositoryEditFormPanel$2.onSubmit(RepositoryEditFormPanel.java:133)
	at org.apache.wicket.ajax.markup.html.form.AjaxSubmitLink$1.onSubmit(AjaxSubmitLink.java:110)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior$AjaxFormSubmitter.onSubmit(AjaxFormSubmitBehavior.java:215)
	at org.apache.wicket.markup.html.form.Form.delegateSubmit(Form.java:1307)
	at org.apache.wicket.markup.html.form.Form.process(Form.java:974)
	at org.apache.wicket.markup.html.form.Form.onFormSubmitted(Form.java:795)
	at org.apache.wicket.ajax.form.AjaxFormSubmitBehavior.onEvent(AjaxFormSubmitBehavior.java:171)
	at org.apache.wicket.ajax.AjaxEventBehavior.respond(AjaxEventBehavior.java:155)
	at org.apache.wicket.ajax.AbstractDefaultAjaxBehavior.onRequest(AbstractDefaultAjaxBehavior.java:588)
	... 115 more
```

**Comment by groldan** [comment]
Closing, the geoserver plugin is obsolete and abandoned.
