### ISSUE TITLE
Sparse clone "Unable to copy filter file" error

### ISSUE THREAD

**Issue by gumenikav** [locationtech/geogig#381]
Geogig V.1.1.1, Win10

I try to make sparse clone:
<pre>
geogig clone ../tst_repo --filter ./myfilter.ini --branch master
</pre>

where myfilter.ini is:
<pre>
[default]
type = CQL
filter = BBOX(geometry,-80,80,-100,100)
</pre>

I receive error:
<pre>
19:12:45.684 [main] ERROR o.locationtech.geogig.cli.GeogigCLI - Unable to copy filter file at path myfilter.ini to the new repository.
java.lang.NullPointerException: null
        at org.locationtech.geogig.di.DecoratorProvider.get(DecoratorProvider.java:34) ~[geogig-core-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.di.GuiceContext.getDecoratedInstance(GuiceContext.java:79) ~[geogig-core-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.di.GuiceContext.blobStore(GuiceContext.java:147) ~[geogig-core-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.repository.impl.RepositoryImpl.blobStore(RepositoryImpl.java:440) ~[geogig-core-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.porcelain.InitOp._call(InitOp.java:141) ~[geogig-core-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.porcelain.InitOp._call(InitOp.java:64) ~[geogig-core-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.repository.AbstractGeoGigOp.call(AbstractGeoGigOp.java:154) ~[geogig-api-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.cli.porcelain.Clone.runInternal(Clone.java:152) ~[geogig-cli-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.cli.AbstractCommand.run(AbstractCommand.java:68) ~[geogig-cli-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.cli.GeogigCLI.executeInternal(GeogigCLI.java:532) ~[geogig-cli-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.cli.GeogigCLI.execute(GeogigCLI.java:368) ~[geogig-cli-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.cli.app.CLI.run(CLI.java:95) [geogig-cli-app-1.1.1.jar:1.1.1]
        at org.locationtech.geogig.cli.app.CLI.main(CLI.java:113) [geogig-cli-app-1.1.1.jar:1.1.1]
Unable to copy filter file at path myfilter.ini to the new repository.
</pre>

**Comment by dinizime** [comment]
Any solution? I have the same problem.

**Comment by dinizime** [comment]
Thats the error that I get:

![Uploading erro_sparse_clone.png…]()
